urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import TemplateView, RedirectView

#import django_cron
#django_cron.autodiscover()
class TextPlainView(TemplateView):
    def render_to_response(self, context, **kwargs):
        return super(TextPlainView, self).render_to_response(
            context, content_type='text/plain', **kwargs)


admin.autodiscover()

urlpatterns = patterns('',

    url(r'^robots\.txt$', RedirectView.as_view(url='/static/robots.txt')),
    url(r'^sitemap\.xml', RedirectView.as_view(url='/static/sitemap.xml')),
    url(r'^xtaoAuth\.txt', RedirectView.as_view(url='/static/xtaoAuth.txt')),
    
    (r'^tinymce/', include('tinymce.urls')),
    (r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    (r'^rosetta/', include('rosetta.urls')),

    (r'^i18n/', include('django.conf.urls.i18n')),
#    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog'),
#    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': ('cart',),}),

    (r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    (r'^static/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.STATIC_ROOT,}),
    (r'^admin/', include(admin.site.urls)),

    (r'shop/', include('shop.urls')),
    (r'statistic/', include('statistic.urls')),

    (r'^', include('cart.urls')),

    (r'^', include('comments.urls')),
    (r'^', include('log.urls')),
    (r'^', include('news.urls')),

    (r'payment/', include('payments.urls')),
    (r'^accounts/', include('registr.urls')),
)

cart/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from shop.models import *
from comments.models import *
from datetime import *
from django.db.models.query import QuerySet
from django.utils.translation import ugettext_lazy as _
# from notification_email import sendEmail
from log.models import *

class QuerySetManager(models.Manager):
    def get_query_set(self):
        return self.model.QuerySet(self.model)
    def __getattr__(self, attr, *args):
        return getattr(self.get_query_set(), attr, *args)



class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey('shop.Product')
    price = models.FloatField(default=0.00,blank=True)
    delivery = models.FloatField(default=0.00,blank=True)
    color = models.ForeignKey('shop.Colors',null=True)
    size = models.ForeignKey('shop.Sizes',null=True)
    type = models.ForeignKey('shop.Types',null=True)
    objects = QuerySetManager()

    def __unicode__(self):
        return str(self.id)

    class QuerySet(QuerySet):
        def full_price(self):
            return sum([x.full_price() for x in self.all()])

        def order_by_shop(self):
            shops=[]
            class Shop:
                pass

            for item in self.all():
                flag = True
                user = item.product.user
                for x in shops:
                    if x.user  == user:
                        flag = False
                if flag:
                    shop=Shop()
                    shop.user = user
                    shop.carts = self.filter(product__user=shop.user)
                    shop.price = sum([x.full_price() for x in shop.carts])

                    shops.append(shop)

            return  shops

    def full_price(self):
        return self.price*self.quantity+self.delivery

    def order(self):
        orders= Order.objects.filter(carts=self)
        return orders[0] if orders else False

    # def complain(self):
    #     from comments.models import Complain
    #
    #     complains = Complain.objects.filter(cart=self)
    #     if complains:
    #      return complains[0]
    #
    #     return  False
    #
    # def is_allowed_complain(self):
    #     #if exist complain
    #     if self.complain():
    #         return True
    #
    #     if not self.product.user.get_profile().trustable:
    #         return False
    #
    #     order = self.order()
    #     today = datetime.now()
    #
    #     #if no complain and order is expired (pass more then 14 days after sending), then return False
    #     if (order.sent_date and (today-order.sent_date).days>=14) or order.status=='Closed':
    #         return False
    #
    #     return True

    def shop(self):
        return self.product.user

    class Meta:
        ordering = ['product__user','-id']



class Order(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(auto_now=True)
    carts  = models.ManyToManyField(CartItem)
    is_payed = models.BooleanField(default=False)
    payed = models.FloatField(default=0.0, blank=True)
    payed_date = models.DateTimeField(blank=True,null=True)

    buyer = models.ForeignKey(User,verbose_name=_(u'Покупатель'))
    seller = models.ForeignKey(User, related_name='seller')

    sent_date = models.DateTimeField(blank=True,null=True)
    track_code = models.CharField(max_length=50)
    delivered_date =models.DateTimeField(blank=True,null=True)

    country = models.CharField(max_length=50)
    region = models.CharField(max_length=50,blank=True)
    city = models.CharField(max_length=50)
    street = models.CharField(max_length=200)
    zip_code = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)

    status = models.CharField(max_length=100)
    is_direct_pay = models.BooleanField(default=False)

    cancelReason = models.TextField(null=True,blank=True)
    is_canceled = models.BooleanField(default=False)

    def price(self):
        return self.carts.all().full_price()

    def balance(self):
        return self.price()-self.payed#-self.released-self.refunded

    def __unicode__(self):
        return str(self.id)

    class Meta:
        ordering = ['-modify_date']

class Address(models.Model):
    country = models.CharField(max_length=50,verbose_name=_(u'Страна'))
    region = models.CharField(max_length=50,blank=True,verbose_name=_(u'Область'))
    city = models.CharField(max_length=50,verbose_name=_(u'Город'))
    street = models.CharField(max_length=200,verbose_name=_(u'Улица'))
    zip_code = models.CharField(max_length=20,verbose_name=_(u'Почтовый индекс'))
    phone = models.CharField(max_length=20,verbose_name=_(u'Телефон'))

    class Meta:
        ordering = ['-id']

templates/manage_shop/base.html
{% extends "base.html" %}
{% load i18n %}
{% load  wall_tags %}
{% block header %} {% endblock %}
{% block body %}
<div class="shop-page">
            <ul class="nav nav-pills nav-stacked breadcrumbs">
                <li class="nav-header">{% trans "Меню продавца:" %}</li>

                <li>
                    <a href="{% url show %}"><i class="icon-home"></i> {% trans "Магазин" %}</a>
                </li>

                <li>
                    <a href="{% url show_my_orders %}"><i class="icon-calendar"></i> {% trans "Показать заказы" %}</a>
                </li>
                <li><a href="{% url contact %}"><i class=" icon-question-sign"></i> {% trans "Контакты" %}</a></li>

            </ul>
        <div class="row">
        {% block big_content %}
            <div class="span8">
                <!-- <form class="well form-search search_main" method="post" action="{% url show %}"> {% csrf_token %}
                    <input type="text" name='search' class="input-medium search-query" placeholder="Search in own shop" value="{{ query }}" >
                    <button type="submit" class="btn btn-info" >Search</button>
                </form> -->

                <!--Body content-->
               {% block content %} {% endblock %}

            </div>
            {% endblock %}
            {% block last_event %}
                    {% display_wall user %}
            {% endblock %}
        </div>
        <!--End of Body content-->
</div>
<script type="text/javascript">
$(function(){
   var path = location.pathname.substring(1);
   if ( path )
     $('.breadcrumbs a[href$="' + path + '"]').attr('class', 'current');
 });
</script>   


{% endblock %}

templates/manage_shop/contacts.html
{% extends "manage_shop/base.html" %}
{% load i18n %}
{% load cart_tags %}

{% block content %}

<div class="contacts">
    <div class="span4"></div>
	<div class="span6">
	  	<h3 class="contacts-head">{% trans "Контакты" %}</h3>
	    <form class="well" method="post" action="">
	        <table class="table table-condensed table-contacts">
	            <tr>
	                <td class="first-sell">{% trans "Магазин:" %}</td>
	                <td><a href="#">{{ user.username }}</a></td>
	            </tr>
                <tr>
                    <td class="first-sell">{% trans "Имя:" %}</td>
                    <td>{{ user.get_profile.name }}</td>
                </tr>
<!-- 	            <tr>
    <td class="first-sell">{% trans "Рейтинг:" %}</td>
    <td>5</td>
</tr> -->
<!-- 	            <tr>
    <td class="first-sell">{% trans "Продаж:" %}</td>
    <td>125</td>
</tr> -->
	            <tr>
	                <td class="first-sell">{% trans "Страна:" %}</td>
                    {% if user.get_profile.country %}
	                    <td class="append-country">{{ user.get_profile.country|countryTrans:LANGUAGE_CODE }}</td>
                    {% endif %}
	            </tr>
                <tr>
                    <td class="first-sell">{% trans "Адрес:" %}</td>
                    <td class="append-country">{{ user.get_profile.address }}</td>
                </tr>
	            <tr>
	                <td class="first-sell">{% trans "Телефон:" %}</td>
	                <td>{{ user.get_profile.phone }}</td>
	            </tr>
	            <tr>
	                <td class="first-sell">{% trans "Skype:" %}</td>
	                <td>{{ user.get_profile.skype }}</td>
	            </tr>
	        </table>
	    </form>
	    <a class="edit-contacts">{% trans "Изменить" %}</a>
	    <div class="clear"></div>
	    <div class="contacts-edit">
	    	<form class="well" method="POST" action=".">{% csrf_token %}
                {{ form }}
{#	    		<div class="control-group">#}
{#		    		<label class="control-label">Укажите страну проживания:</label>#}
{#		    		<input type="text" placeholder="Страна">#}
{#	    		</div>#}
{#	    		<div class="control-group">#}
{#		    		<label class="control-label">Укажите ваш номер телефона:</label>#}
{#		    		<input type="text" placeholder="Пример: 380991111111">#}
{#	    		</div>#}
{#	    		<div class="control-group">#}
{#		    		<label class="control-label">Укажите ваш ник в Skype:</label>#}
{#		    		<input type="text" placeholder="Skype">#}
{#	    		</div>#}
	    		<div class="form-actions">
	    			<button type="submit" class="btn btn-warning">{% trans "Сохранить изменения" %}</button>
	    		</div>
			</form>
	    </div>
	</div>
</div>

<script type="text/javascript">
	$('.edit-contacts').on('click', function() {
		$('.contacts-edit').fadeToggle('300');
	})
	$('.close-contacts').on('click', function() {
		$('.contacts-edit').css('display', 'none');
	})
    {% if form.errors %}
    $('.contacts-edit').fadeToggle('300');
    {% endif %}
</script>
{% endblock %}

templates/manage_shop/orders.html
{% extends "manage_shop/base.html" %}
{% load cart_tags %}
{% load i18n %}

{% block content %}
<style type="text/css">
.delivery, .quantity, .price {
    width: 50px;
}
</style>
<script type="text/javascript" src="/static/scripts/order_manager/changes.js"></script>

<script>
  $(function () {
    $('#tabs-orders a:first').tab('show');
      function getURLParameter(name) {
          return decodeURI(
                  (RegExp(name + '=' + '(.+?)(&|$)').exec(location.search)||[,null])[1]
          );
      }
      if (getURLParameter('tab')=='second')
        $('.notpayed-link').click();
      if (getURLParameter('tab')=='third')
          $('.closed-link').click();
  })
</script>
<div id="orders">

    {% if payed_orders.object_list or not_payed_orders.object_list or closed_orders.object_list%}
    <ul class="nav nav-tabs" id="tabs-orders">
        <li><a class="payed-link" href="#payed" data-toggle="tab">{% trans "Неоплаченные заказы" %}</a></li>
        <li><a class="closed-link" href="#closed" data-toggle="tab">{% trans "Завершенные сделки" %}</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" id="payed">
            {% for order in not_payed_orders.object_list %}
                {% include "tags/order.html" with order=order track='True' payed='True' who='seller'%}
            {% endfor %}
            {% if not_payed_orders.paginator.num_pages != 1 %}
            <ul class="paginator">
                {% if not_payed_orders.has_previous %}
                    <li class="page-prev"><a href="?page={{ not_payed_orders.previous_page_number }}"> ← </a></li>
                {% endif %}
                    {{ not_payed_orders.number }}  {% trans "из" %}  {{ not_payed_orders.paginator.num_pages }}

                {% if not_payed_orders.has_next %}
                    <li class="page-next"><a href="?page={{ not_payed_orders.next_page_number }}"> → </a></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>

        <div class="tab-pane" id="closed">
            {% for order in closed_orders.object_list %}
                {% include "tags/order.html" with order=order  who='seller'%}
            {% endfor %}
            {% if closed_orders.paginator.num_pages != 1 %}
            <ul class="paginator">
                {% if closed_orders.has_previous %}
                    <li class="page-prev"><a href="?page3={{ closed_orders.previous_page_number }}&tab=third"> ← </a></li>
                {% endif %}
                    {{ closed_orders.number }}  {% trans "из" %}  {{ closed_orders.paginator.num_pages }}
                {% if closed_orders.has_next %}
                    <li class="page-next"><a href="?page3={{ closed_orders.next_page_number }}&tab=third"> → </a></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>

    {% else %}
        {% trans "У вас пока нет заказов" %}
        <span class="sadsmile">:(</span>
    {% endif %}
</div>
<script>
    $('#not_payed .collapse').first().addClass('in');
    $('#payed .collapse').first().addClass('in');
    $('#closed .collapse').first().addClass('in');
    $('.accordion-toggle:even').css('background', '#DFDFDF');
</script>
{% endblock %}

templates/manage_shop/search.html
{% extends "manage_shop/base.html" %}
{% load i18n %}
{% block content %}

    <div class="add-prod-holder">
        <a href="{%  url add_product %}" class="addproduct btn btn-large btn btn-warning">{% trans "Добавить новый товар" %}</a>
    </div>
    <div class="clear"></div>
    
    {% if products.object_list %}
    <div class="artsearch">
        <form action="." method="GET">
            <input type="text" name="search" placeholder="Поиск по товарам (название, штрих код и т.д.)">
            <button class="btn">Поиск</button>
        </form>
    </div>
    <div class="quick-actions">
        <form action="{% url action %}" method="post" class="confirm" rel="{% trans "Уверены ?" %}">{% csrf_token %}
        <select name="action">
            <option value="del_choosen">{% trans "Удалить выбраные" %}</option>
            <option value="del_all">{% trans "Удалить все" %}</option>
        </select>
        <button class="btn">Ok</button>
    </div>
        <table class="table table-striped table-condensed table-search-prod">
            <thead>
            <tr>
                <th></th>
                <th><span class="label">{% trans "Фото" %}</span></th>
                <th><span class="label">{% trans "Название" %}</span></th>
                <th class="th-price"><span class="label">{% trans "Цена" %}</span></th>
                <th><span class="label">{% trans "Количество" %}</span></th>
                {#                <th><span class="label">Edit item</span></th>#}
                <th class="td-del"><span class="label">{% trans "Удаление" %}</span></th>
            </tr>
            </thead>
            <tbody>
            {% for product in products.object_list %}
                <tr>
                    <td class="checker">
                        <input name ="product_{{ product.id }}" type="checkbox">
                    </td>
                    <td><a href="{% url edit_product product.id %}" class="item_pic"><img src="/media/{{ product.small_picture }}" width="64px" alt=""></a></td>
                    <td>
                        <a href="{% url edit_product product.id %}"> {{ product.name }}</a>
                        {% if product.link %}
                            <a class="plugin-link" href="{{ product.link }}" target="_blank">Link</a>
                        {% endif %}
                    </td>


                    <td>{{ product.price }} грн.</td>
                    <td>{{ product.quantity }}</td>
                    {#                <td><a href="#"><span class="label label-warning"><i class="icon-pencil icon-white"></i> Edit</span></a></td>#}
                    <td class="td-del">
                        <a class="confirm" rel='{% trans "Вы уверены что хотите удалить этот товар?" %}' href="{% url delete_product product.id%}" title="{% trans "Удалить" %}">
                            <span class="label label-important"><i class="icon-trash icon-white"></i></span></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        </form>
        <ul class="paginator">
            {% if products.has_previous %}
                <li class="page-prev"><a href="?q={{ query }}&page={{ products.previous_page_number }}" id="previous"> ← </a></li>
            {% endif %}
            {{ products.number }}  {% trans "из" %}  {{ products.paginator.num_pages }}.
            {% if products.has_next %}
                <li class="page-next"><a href="?q={{ query }}&page={{ products.next_page_number }}" id="next"> → </a></li>
            {% endif %}
        </ul>
    {% else %}
        <div class="hero-unit">
            <p>{% trans "У вас пока нет ни одного товара.  Просто нажмите кнопку 'Добавить новый товар'' и начинайте зарабатывать прямо сейчас!" %}</p>
        </div>
        
    {% endif %}


{% if not user.get_profile.phone %}
<script>
    $(function () {
        $('.addproduct').on('click', function(e) {
            e.preventDefault();
            $('#contactsplease').modal('show');
        });
    });
</script>
{% endif %}


<div id="contactsplease" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Укажите ваш номер телефона</h3>
  </div>
  <div class="modal-body">
  <p>Мы заметили, что вы не указали номер вашего телефона в ваших <a href="/contacts/">контактах</a>.</p>
  <p>Пожалуйста, укажите его, прежде чем добавить свой первый товар. Это позволит повысить степень доверия покупателей и увеличит ваши продажи.</p>
    <form method="POST" action="/shop/contacts/">{% csrf_token %}
        <input type="hidden" name="next" value="add_product">
        <input type="hidden" name="country" value="Ukraine">
        <label for="id_phone">Телефон:</label><input id="id_phone" type="text" name="phone" maxlength="20">
        <button type="submit" class="btn btn-warning">{% trans "Сохранить изменения" %}</button>
    </form>
  </div>
</div>


{% endblock %}